typography_spectrum: 0.6457321369089186
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5312115387059748
  lightness: 0.8748223523143679
  saturation: 0.6772215189412236
  rhythmicContrast: 0.004140405682846904
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9447537495288998
analytics:
  google: null
  facebook: null
  twitter: null
name: Social Revolution
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: I. LAYING PLANS
    id: 37fffe34-11f1-4b1f-9909-aa721605361b
    type: content
favicon: null
title: Manifesto
description: For exponential growth
purpose: []
